swagger: '2.0'
info:
  version: 0.0.1
  title: Match API
  description: Match API description
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: Use 'Bearer <access_token>' to authenticate requests.
